resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/danwiltshire/experiments-with-concourse.git

jobs:
  - name: configure-self
    plan:
      - get: repo
        trigger: true
      - set_pipeline: self
        file: repo/concourse/hello-world.yml

  - name: hello-world-job
    plan:
      - get: repo
        trigger: true
        passed: [configure-self]

      - task: hello-world-task
        config:
          # Tells Concourse which type of worker this task should run on
          platform: linux
          # This is one way of telling Concourse which container image to use for a
          # task. We'll explain this more when talking about resources
          image_resource:
            type: registry-image
            source:
              repository: busybox # images are pulled from docker hub by default
              tag: latest
          # The command Concourse will run inside the container
          # echo "Hello world!"
          run:
            path: echo
            args: ["Hello world!"]
