resources:
  - name: repo
    type: git
    icon: github
    check_every: 10s
    source:
      uri: https://github.com/danwiltshire/experiments-with-concourse.git

var_sources:
  - name: awstoken
    type: idtoken
    config:
      audience: ["sts.amazonaws.com"]

jobs:
  - name: test
    plan:
      - get: repo
        trigger: true

      - task: oidc-s3-ls
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: "24" }
          inputs:
            - name: repo
          params:
            aws_role_arn: arn:aws:iam::123456789012:role/concourse-main-hello-world-oidc
            aws_oidc_token: ((awstoken:token))
          run:
            path: bash
            args:
              - -ec
              - |
                apt-get update -qq && apt-get install -y --no-install-recommends awscli

                source repo/concourse/scripts/aws-oidc-auth.sh

                aws s3 ls
